/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xI2AyeyS9L3
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Afacad } from 'next/font/google'
import { Archivo } from 'next/font/google'

afacad({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

"use client"
import { Card, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Button } from "@/components/ui/button"
import { useState } from "react"


export function CreateJob() {
  const [jobTitle, setJobTitle] = useState('Job title')

  return (
    <Card className="max-w-2xl mx-auto p-6 sm:p-8 md:p-10">
      <div className="flex items-center justify-between mb-6">
        <img src="/placeholder.svg" width="100" height="50" alt="Company Logo" className="object-contain" />
        <CardTitle className="text-3xl font-bold">Create a New Job Posting</CardTitle>
      </div>
      <CardDescription>Fill out the form below to generate a unique job listing.</CardDescription>
      <CardContent>
        <form className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="grid gap-4">
            <div className="grid gap-2">
              <Label htmlFor="job-title" className="text-sm font-medium">
                Job Title
              </Label>
              <Input id="job-title" placeholder="Software Engineer" onChange={(e)=>setJobTitle(e.target.value)} />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="job-description" className="text-sm font-medium">
                Job Description
              </Label>
              <Textarea id="job-description" rows={5} placeholder="Describe the role and responsibilities..." />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="sector" className="text-sm font-medium">
                Sector
              </Label>
              <Select id="sector">
                <SelectTrigger>
                  <SelectValue placeholder="Select sector" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="technology">Technology</SelectItem>
                  <SelectItem value="finance">Finance</SelectItem>
                  <SelectItem value="healthcare">Healthcare</SelectItem>
                  <SelectItem value="retail">Retail</SelectItem>
                  <SelectItem value="education">Education</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="grid gap-2">
              <Label htmlFor="experience-level" className="text-sm font-medium">
                Experience Level
              </Label>
              <Select id="experience-level">
                <SelectTrigger>
                  <SelectValue placeholder="Select experience level" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="entry">Entry Level</SelectItem>
                  <SelectItem value="mid">Mid Level</SelectItem>
                  <SelectItem value="senior">Senior Level</SelectItem>
                  <SelectItem value="executive">Executive Level</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <div className="grid gap-4">
            <div className="grid gap-2">
              <Label htmlFor="job-number" className="text-sm font-medium">
                Job Number
              </Label>
              <div className="flex items-center gap-2">
                <Input id="job-number" type="text" placeholder="123456" readOnly />
                <Button type="button" variant="outline" className="bg-[#ffd700] text-[#333] hover:bg-[#ffeb8d]">
                  Generate
                </Button>
              </div>
            </div>
            <div className="grid gap-2">
              <Label className="text-sm font-medium">Job Posting Preview</Label>
              <div className="bg-[#f5f5f5] p-4 rounded-md">
                <div className="flex items-center justify-between">
                  <div className="text-2xl font-bold">{jobTitle}</div>
                  <div className="bg-[#ffd700] px-3 py-1 rounded-full text-[#333] font-bold">#123456</div>
                </div>
                <p className="text-muted-foreground mt-2">
                  Seeking a talented Software Engineer to join our dynamic team. Responsibilities include designing and
                  developing scalable web applications, collaborating with cross-functional teams, and contributing to
                  the overall success of the organization.
                </p>
                <div className="flex items-center gap-2 mt-4">
                  <div className="bg-[#e6e6e6] px-3 py-1 rounded-full text-sm font-medium">Technology</div>
                  <div className="bg-[#e6e6e6] px-3 py-1 rounded-full text-sm font-medium">Mid Level</div>
                </div>
              </div>
            </div>
          </div>
        </form>
      </CardContent>
      <CardFooter>
        <div className="flex justify-end">
          <Button type="submit" className="bg-[#ffd700] text-[#333] hover:bg-[#ffeb8d]">
            Post Job
          </Button>
        </div>
      </CardFooter>
    </Card>
  )
}
